// Code generated by protoc-gen-go. DO NOT EDIT.

package proto

import (
	_ "google.golang.org/protobuf/types/known/anypb"
	
)

type PaymentRequest struct {
	UserId string  `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Amount float64 `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Method string  `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
}

type Notification struct {
	UserId  string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}
