name: Go Microservices CI/CD

on:
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      zookeeper:
        image: bitnami/zookeeper:latest
        ports:
          - 2181:2181

      kafka:
        image: bitnami/kafka:latest
        ports:
          - 9092:9092
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_LISTENERS: PLAINTEXT://:9092
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Debug Go Env
      run: |
        which go
        go version
        go help mod

    - name: Build Payment Service
      working-directory: ./payment-service
      run: |
        go mod tidy
        go build -o main .

    - name: Build Notification Service
      working-directory: ./notification-service
      run: |
        go mod tidy
        go build -o main .

    - name: Run Unit Tests (Optional)
      run: echo "Add tests if needed"
